apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kifk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-kifk@sha256:2d787ab4dbf3f3342c83fb5c69dee1a530d8c87bb38819f4b948f03a33448069
        name: my-nodejs
        resources: {}
status: {}
